"use client";

import { useState } from "react";
import { Boxes, ChevronRight, CircleDollarSign, LayoutDashboard, Menu, PackageSearch, Plus, Search, ShoppingCart, SlidersHorizontal, X } from "lucide-react";
import type { LucideIcon } from "lucide-react";

type Product = { id: string; name: string; category: string; price: number; stock: number; minimum: number; unit: string; color: string };
const products: Product[] = [
  { id: "p1", name: "Nước suối Aquafina 500ml", category: "Đồ uống", price: 7000, stock: 8, minimum: 12, unit: "chai", color: "cyan" },
  { id: "p2", name: "Mì Hảo Hảo tôm chua cay", category: "Thực phẩm", price: 4500, stock: 64, minimum: 20, unit: "gói", color: "lime" },
  { id: "p3", name: "Sữa tươi Vinamilk 180ml", category: "Sữa", price: 8500, stock: 11, minimum: 15, unit: "hộp", color: "indigo" },
  { id: "p4", name: "Bánh quy Cosy 300g", category: "Bánh kẹo", price: 28000, stock: 27, minimum: 10, unit: "gói", color: "orange" },
  { id: "p5", name: "Nước rửa chén Sunlight 750ml", category: "Gia dụng", price: 32000, stock: 5, minimum: 8, unit: "chai", color: "pink" },
];
const money = (v: number) => `${v.toLocaleString("vi-VN")}đ`;
const nav = [{ label: "Tổng quan", icon: LayoutDashboard }, { label: "Bán hàng", icon: ShoppingCart }, { label: "Sản phẩm", icon: PackageSearch }, { label: "Tồn kho", icon: Boxes }];
const flowNodes: { code: string; label: string; value: string; color: string; icon: LucideIcon }[] = [
  { code: "IN", label: "NHẬP KHO", value: "+240", color: "indigo", icon: Boxes },
  { code: "ST", label: "TỒN KHO", value: "1.248", color: "lime", icon: PackageSearch },
  { code: "OUT", label: "BÁN HÀNG", value: "86 TX", color: "cyan", icon: ShoppingCart },
  { code: "REV", label: "DOANH THU", value: "12,48M", color: "orange", icon: CircleDollarSign },
];

function Metric({ label, value, detail, color }: { label: string; value: string; detail: string; color: string }) { return <article className={`metric ${color}`}><small><i />{label}</small><strong>{value}</strong><span>{detail}</span></article>; }

export default function Home() {
  const [active, setActive] = useState("Tổng quan");
  const [query, setQuery] = useState("");
  const [cart, setCart] = useState<Product[]>([]);
  const [inspector, setInspector] = useState<Product | null>(products[0]);
  const [menu, setMenu] = useState(false);
  const [paid, setPaid] = useState(false);
  const [showLowStockOnly, setShowLowStockOnly] = useState(false);
  const [showReceiveForm, setShowReceiveForm] = useState(false);
  const [receiveProductId, setReceiveProductId] = useState(products[0].id);
  const [receiveQuantity, setReceiveQuantity] = useState("10");
  const visible = products.filter((p) => p.name.toLowerCase().includes(query.toLowerCase()));
  const total = cart.reduce((sum, p) => sum + p.price, 0);
  const add = (p: Product) => { if (!cart.some((item) => item.id === p.id)) setCart([...cart, p]); };
  const newOrder = () => { setCart([]); setQuery(""); setPaid(false); setActive("Bán hàng"); };
  return <main className={`app-shell module-${active === "Tổng quan" ? "dashboard" : active === "Bán hàng" ? "sales" : active === "Sản phẩm" ? "products" : active === "Tồn kho" ? "inventory" : "other"}`}>
    <header className="topbar"><button className="icon mobile-menu" onClick={() => setMenu(!menu)} aria-label="Mở menu"><Menu size={18} /></button><div className="brand"><b>M</b><span>MYSHOP <em>/</em> OPS NODE</span></div><div className="telemetry"><span>● SYNC ONLINE</span><span>LATENCY <b>24ms</b></span><strong>OWNER</strong><small>25 AUG 2026 / 09:42</small></div></header>
    <div className="workspace"><aside className={`sidebar ${menu ? "open" : ""}`}><label>COMMAND CENTER</label>{nav.map(({ label, icon: Icon }) => <button key={label} className={active === label ? "active" : ""} onClick={() => { setActive(label); setMenu(false); }}><Icon size={17} />{label}{label === "Tồn kho" && <i>3</i>}</button>)}<div className="sidebar-bottom"><button><SlidersHorizontal size={17} />Thiết lập</button><div className="user"><b>H</b><span>Huy Nguyen<small>Chủ cửa hàng</small></span><i /></div></div></aside>
      <section className="canvas"><div className="heading"><div><small>STORE / PRIMARY NODE / 01</small><h1>{active.toUpperCase()}</h1><p>Thứ Ba, 25 tháng 8, 2026 <em>//</em> Ca sáng đang hoạt động</p></div><button className="primary" onClick={newOrder}><Plus size={16} /> BÁN HÀNG MỚI</button></div>
        {active === "Bán hàng" ? <SalesView products={products} cart={cart} setCart={setCart} query={query} setQuery={setQuery} paid={paid} setPaid={setPaid} onNewOrder={newOrder} /> : active === "Sản phẩm" ? <ProductsView products={products} setInspector={setInspector} /> : active === "Tồn kho" ? <InventoryView products={products} setInspector={setInspector} showLowStockOnly={showLowStockOnly} setShowLowStockOnly={setShowLowStockOnly} showReceiveForm={showReceiveForm} setShowReceiveForm={setShowReceiveForm} receiveProductId={receiveProductId} setReceiveProductId={setReceiveProductId} receiveQuantity={receiveQuantity} setReceiveQuantity={setReceiveQuantity} /> : <DashboardView products={products} setInspector={setInspector} setActive={setActive} />}
        <div className="grid-two lower"><section className="panel"><header><div><small>INVENTORY / ALERTS</small><h2>CẦN NHẬP KHO</h2></div><button className="link">XEM TẤT CẢ <ChevronRight size={13} /></button></header><table><thead><tr><th>SẢN PHẨM</th><th>TỒN</th><th>TỐI THIỂU</th><th>TRẠNG THÁI</th></tr></thead><tbody>{products.filter((p) => p.stock <= p.minimum).map((p) => <tr key={p.id} onClick={() => setInspector(p)}><td><i className={`swatch ${p.color}`} /><span><b>{p.name}</b><small>{p.category} / {p.unit}</small></span></td><td className="low">{p.stock}</td><td>{p.minimum}</td><td><em className="warning">CẦN NHẬP</em></td></tr>)}</tbody></table></section><section className="panel"><header><div><small>ACTIVITY / RECENT</small><h2>GIAO DỊCH GẦN ĐÂY</h2></div><button className="icon"><SlidersHorizontal size={15} /></button></header>{[["#MS-0086", "09:38", "128.000đ"], ["#MS-0085", "09:31", "452.500đ"], ["#MS-0084", "09:27", "76.000đ"], ["#MS-0083", "09:11", "214.000đ"]].map(([id, time, amount]) => <div className="activity" key={id}><span>↗</span><p><b>{id}</b><small>{time} / CASH</small></p><strong>{amount}</strong><i>✓</i></div>)}</section></div>
      </section>{inspector && <aside className="inspector"><header><div><small>INSPECTOR / PRODUCT</small><h2>CHI TIẾT SẢN PHẨM</h2></div><button className="icon" onClick={() => setInspector(null)}><X size={16} /></button></header><div className="product-detail"><i className={`large-swatch ${inspector.color}`} /><small>{inspector.category}</small><h3>{inspector.name}</h3><p>SKU-{inspector.id.toUpperCase()} / {inspector.unit}</p></div><div className="stats"><div><small>TỒN HIỆN TẠI</small><b className="low">{inspector.stock}</b><span>{inspector.unit}</span></div><div><small>TỐI THIỂU</small><b>{inspector.minimum}</b><span>{inspector.unit}</span></div><div><small>GIÁ BÁN</small><b>{money(inspector.price)}</b><span>/ {inspector.unit}</span></div></div><div className="detail-section"><small>TRẠNG THÁI <em className="warning">LOW STOCK</em></small><div className="meter"><i style={{ width: `${Math.min(inspector.stock / (inspector.minimum * 2) * 100, 100)}%` }} /></div><p>Cần bổ sung {Math.max(inspector.minimum * 2 - inspector.stock, 0)} {inspector.unit} để đạt mức an toàn.</p></div><div className="detail-section"><small>RAW DATA <ChevronRight size={13} /></small><pre>{JSON.stringify({ id: inspector.id, stock: inspector.stock, minimum: inspector.minimum, active: true }, null, 2)}</pre></div><button className="primary full"><Boxes size={15} /> ĐIỀU CHỈNH TỒN KHO</button></aside>}</div>
    <footer><span>● HỆ THỐNG ỔN ĐỊNH <em>|</em> LAST SYNC 09:42:18</span><div><button onClick={() => { setActive("Tồn kho"); setShowReceiveForm(true); }}><Plus size={14} /> NHẬP KHO</button><button className="primary" onClick={newOrder}><ShoppingCart size={14} /> BÁN HÀNG MỚI <b>F4</b></button></div></footer>
    {active === "Bán hàng" && <div className="sales"><header><div><small>CHECKOUT / QUICK SALE</small><h2>BÁN HÀNG MỚI</h2></div><button className="icon" onClick={() => setActive("Tổng quan")}><X size={17} /></button></header><div className="search"><Search size={16} /><input autoFocus placeholder="Tìm tên sản phẩm hoặc mã vạch..." value={query} onChange={(e) => setQuery(e.target.value)} /></div>{visible.map((p) => <button className="result" key={p.id} onClick={() => add(p)}><i className={`swatch ${p.color}`} /><span><b>{p.name}</b><small>{p.category} / còn {p.stock} {p.unit}</small></span><strong>{money(p.price)}</strong><Plus size={15} /></button>)}<div className="cart"><small>GIỎ HÀNG / {cart.length} SẢN PHẨM</small>{cart.map((p) => <p key={p.id}>{p.name}<b>{money(p.price)}</b></p>)}<div className="total"><span>TỔNG THANH TOÁN</span><strong>{money(total)}</strong></div><button className="pay" onClick={() => setPaid(true)}>{paid ? "ĐÃ THANH TOÁN ✓" : "XÁC NHẬN THANH TOÁN"}</button></div></div>}
  </main>;
}
function DashboardView({ products, setInspector, setActive }: { products: Product[]; setInspector: (product: Product) => void; setActive: (label: string) => void }) {
  return <>
    <div className="metrics"><Metric label="DOANH THU HÔM NAY" value="12.480.000đ" detail="+18,4% so với hôm qua" color="lime" /><Metric label="GIAO DỊCH" value="86" detail="12 giao dịch trong giờ qua" color="indigo" /><Metric label="LỢI NHUẬN GỘP ƯỚC TÍNH" value="3.210.000đ" detail="Biên lợi nhuận 25,7%" color="cyan" /><Metric label="GIÁ TRỊ TỒN KHO" value="48.920.000đ" detail="3 mặt hàng cần nhập" color="orange" /></div>
    <div className="grid-two"><section className="panel"><header><div><small>LIVE FLOW / 001</small><h2>DÒNG VẬN HÀNH</h2></div><span className="live">● LIVE</span></header><div className="nodes">{flowNodes.map(({ code, label, value, color, icon: Icon }) => <div className={`node ${color}`} key={code}><div><span>{code}</span><Icon size={15} /></div><strong>{value}</strong><small>{label}</small><i>● ổn định</i></div>)}</div></section><section className="panel chart-panel"><header><div><small>TELEMETRY / REVENUE</small><h2>DOANH THU</h2></div><button className="select">7 NGÀY <ChevronRight size={13} /></button></header><strong className="chart-total">12,48M <em>+18,4%</em></strong><div className="chart"><svg viewBox="0 0 640 180" preserveAspectRatio="none"><path d="M0 150 C50 145 75 152 115 115 S175 128 210 94 S260 102 300 75 S350 90 390 55 S440 70 475 45 S530 58 565 23 S610 42 640 8" fill="none" stroke="#c7f000" strokeWidth="2" /></svg><div><span>T2</span><span>T3</span><span>T4</span><span>T5</span><span>T6</span><span>T7</span><span>CN</span></div></div></section></div>
    <button className="primary" onClick={() => setActive("Bán hàng")}><ShoppingCart size={15} /> MỞ QUẦY BÁN HÀNG</button>
  </>;
}

function SalesView({ products, cart, setCart, query, setQuery, paid, setPaid, onNewOrder }: { products: Product[]; cart: Product[]; setCart: (items: Product[]) => void; query: string; setQuery: (value: string) => void; paid: boolean; setPaid: (value: boolean) => void; onNewOrder: () => void }) {
  const visible = products.filter((product) => product.name.toLowerCase().includes(query.toLowerCase()));
  const total = cart.reduce((sum, product) => sum + product.price, 0);
  return <section className="sales-page panel"><div className="sales-layout"><div><div className="section-heading"><div><small>CHECKOUT / QUICK SALE</small><h2>QUẦY THANH TOÁN</h2></div><span className="live">● READY</span></div><div className="search"><Search size={16} /><input autoFocus disabled={paid} placeholder="Tìm tên sản phẩm hoặc mã vạch..." value={query} onChange={(event) => setQuery(event.target.value)} /></div><div className="result-list">{visible.map((product) => <button className="result" disabled={paid || cart.some((item) => item.id === product.id)} key={product.id} onClick={() => setCart([...cart, product])}><i className={`swatch ${product.color}`} /><span><b>{product.name}</b><small>{product.category} / còn {product.stock} {product.unit}</small></span><strong>{money(product.price)}</strong><Plus size={15} /></button>)}</div></div><div className="checkout"><small>GIỎ HÀNG / {cart.length} SẢN PHẨM</small>{cart.map((product) => <p key={product.id}>{product.name}<b>{money(product.price)}</b></p>)}<div className="total"><span>TỔNG THANH TOÁN</span><strong>{money(total)}</strong></div><div className="payment-tabs"><button className="selected">TIỀN MẶT</button><button>THẺ</button><button>MOBILE</button></div>{paid ? <button className="pay new-order" onClick={onNewOrder}><Plus size={15} /> TẠO ĐƠN HÀNG MỚI</button> : <button className="pay" disabled={cart.length === 0} onClick={() => setPaid(true)}>THANH TOÁN</button>}</div></div></section>;
}

function ProductsView({ products, setInspector }: { products: Product[]; setInspector: (product: Product) => void }) {
  return <section className="module-page panel"><div className="section-heading"><div><small>CATALOG / PRODUCTS</small><h2>DANH MỤC SẢN PHẨM</h2></div><button className="primary"><Plus size={15} /> THÊM SẢN PHẨM</button></div><div className="module-toolbar"><div className="search"><Search size={16} /><input placeholder="Tìm tên hoặc mã vạch..." /></div><button className="select">TẤT CẢ <ChevronRight size={13} /></button></div><table><thead><tr><th>SẢN PHẨM</th><th>DANH MỤC</th><th>GIÁ BÁN</th><th>TỒN KHO</th><th>TRẠNG THÁI</th></tr></thead><tbody>{products.map((product) => <tr key={product.id} onClick={() => setInspector(product)}><td><i className={`swatch ${product.color}`} /><span><b>{product.name}</b><small>SKU-{product.id.toUpperCase()} / {product.unit}</small></span></td><td>{product.category}</td><td>{money(product.price)}</td><td className={product.stock <= product.minimum ? "low" : ""}>{product.stock}</td><td><em className={product.stock <= product.minimum ? "warning" : "ok-tag"}>{product.stock <= product.minimum ? "TỒN THẤP" : "ĐANG BÁN"}</em></td></tr>)}</tbody></table></section>;
}

function InventoryView({ products, setInspector, showLowStockOnly, setShowLowStockOnly, showReceiveForm, setShowReceiveForm, receiveProductId, setReceiveProductId, receiveQuantity, setReceiveQuantity }: { products: Product[]; setInspector: (product: Product) => void; showLowStockOnly: boolean; setShowLowStockOnly: (value: boolean) => void; showReceiveForm: boolean; setShowReceiveForm: (value: boolean) => void; receiveProductId: string; setReceiveProductId: (value: string) => void; receiveQuantity: string; setReceiveQuantity: (value: string) => void }) {
  const visibleProducts = showLowStockOnly ? products.filter((product) => product.stock <= product.minimum) : products;
  const receive = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setShowReceiveForm(false); setReceiveQuantity("10"); };
  return <section className="module-page panel"><div className="section-heading"><div><small>INVENTORY / CONTROL</small><h2>QUẢN LÝ TỒN KHO</h2></div><button className="primary" onClick={() => setShowReceiveForm(true)}><Plus size={15} /> NHẬP KHO</button></div><div className="inventory-alert"><Boxes size={17} /><span><b>{products.filter((product) => product.stock <= product.minimum).length} sản phẩm cần xử lý</b><small>Các mặt hàng đã chạm ngưỡng tồn tối thiểu</small></span><button className="link" onClick={() => setShowLowStockOnly(!showLowStockOnly)}>{showLowStockOnly ? "XEM TẤT CẢ" : "XEM CẢNH BÁO"} <ChevronRight size={13} /></button></div>{showReceiveForm && <form className="receive-form" onSubmit={receive}><div><label>SẢN PHẨM</label><select value={receiveProductId} onChange={(event) => setReceiveProductId(event.target.value)}>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></div><div><label>SỐ LƯỢNG NHẬP</label><input type="number" min="1" value={receiveQuantity} onChange={(event) => setReceiveQuantity(event.target.value)} required /></div><button className="primary" type="submit">XÁC NHẬN NHẬP KHO</button></form>}<table><thead><tr><th>SẢN PHẨM</th><th>TỒN HIỆN TẠI</th><th>MỨC TỐI THIỂU</th><th>BIẾN ĐỘNG</th><th>TRẠNG THÁI</th></tr></thead><tbody>{visibleProducts.map((product) => <tr key={product.id} onClick={() => setInspector(product)}><td><i className={`swatch ${product.color}`} /><span><b>{product.name}</b><small>Cập nhật 09:42 / {product.unit}</small></span></td><td className={product.stock <= product.minimum ? "low" : "stock-good"}>{product.stock}</td><td>{product.minimum}</td><td className="stock-good">+12</td><td><em className={product.stock <= product.minimum ? "warning" : "ok-tag"}>{product.stock <= product.minimum ? "CẦN NHẬP" : "ỔN ĐỊNH"}</em></td></tr>)}</tbody></table></section>;
}
